---
- hosts: 172.31.1.220
  become: yes
  tasks: 
  - name: i want to install linux command
    command: hostname -f
    register: myfirsttaskresult
  - name: i want to display firsttaskresult
    debug:
      msg: "{{myfirsttaskresult}}"  