--- 
- hosts: all 
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu/redhat nodes
    apt:
     name: https 
     state: present 
    when: ansible_os_family =="Debian"

  - name: i want to start webserver
    service:
     name: https
     state: started 
    when: ansible_os_family =="Debian"

# "RedHat"=="Debian"        