---
- hosts: all 
  becomes: yes
  tasks: 
  - name: i want to install git on ubuntu nodes
    apt:
     name: git 
     state: present 

  - name: i want to install tree on ubuntu nodes
    apt:
     name: tree
     state: present  